export type ArcanaType = "maior" | "menor"

export type MinorSuit = "paus" | "copas" | "espadas" | "ouros"

export interface TarotCard {
  slug: string
  number: string
  name: string
  type: ArcanaType
  suit?: MinorSuit
  keywords: string[]
  upright: string
  reversed: string
  description: string
}

export const suitInfo: Record<
  MinorSuit,
  { name: string; element: string; theme: string; symbol: string }
> = {
  paus: {
    name: "Paus",
    element: "Fogo",
    theme: "Energia, paixão, criatividade e ação",
    symbol: "🜂",
  },
  copas: {
    name: "Copas",
    element: "Água",
    theme: "Emoções, relacionamentos e intuição",
    symbol: "🜄",
  },
  espadas: {
    name: "Espadas",
    element: "Ar",
    theme: "Pensamento, conflito, verdade e intelecto",
    symbol: "🜁",
  },
  ouros: {
    name: "Ouros",
    element: "Terra",
    theme: "Material, trabalho, dinheiro e corpo",
    symbol: "🜃",
  },
}

export const majorArcana: TarotCard[] = [
  {
    slug: "o-louco",
    number: "0",
    name: "O Louco",
    type: "maior",
    keywords: ["Início", "Espontaneidade", "Liberdade"],
    upright: "Novos começos, fé no desconhecido, aventura e inocência.",
    reversed: "Imprudência, decisões precipitadas, medo de arriscar.",
    description:
      "O Louco representa o início da jornada, o salto de fé rumo ao desconhecido. Carrega a pureza de quem ainda não foi moldado pela experiência e convida à confiança no fluxo da vida.",
  },
  {
    slug: "o-mago",
    number: "I",
    name: "O Mago",
    type: "maior",
    keywords: ["Manifestação", "Poder", "Habilidade"],
    upright: "Capacidade de criar, foco, domínio dos recursos disponíveis.",
    reversed: "Manipulação, talentos desperdiçados, falta de clareza.",
    description:
      "O Mago é aquele que reúne os quatro elementos e transforma vontade em realidade. Simboliza o poder da concentração e a ponte entre o céu e a terra.",
  },
  {
    slug: "a-sacerdotisa",
    number: "II",
    name: "A Sacerdotisa",
    type: "maior",
    keywords: ["Intuição", "Mistério", "Sabedoria interior"],
    upright: "Conhecimento oculto, intuição, silêncio e contemplação.",
    reversed: "Segredos revelados, desconexão da intuição, confusão.",
    description:
      "A Sacerdotisa guarda os mistérios entre o consciente e o inconsciente. Ela ensina a escutar a voz interior antes de qualquer ação.",
  },
  {
    slug: "a-imperatriz",
    number: "III",
    name: "A Imperatriz",
    type: "maior",
    keywords: ["Abundância", "Fertilidade", "Cuidado"],
    upright: "Criatividade fértil, nutrição, prosperidade e beleza.",
    reversed: "Bloqueio criativo, dependência, descuido consigo mesmo.",
    description:
      "A Imperatriz é a mãe da natureza, símbolo de fartura e criação. Representa o florescimento de projetos e o cuidado generoso com a vida.",
  },
  {
    slug: "o-imperador",
    number: "IV",
    name: "O Imperador",
    type: "maior",
    keywords: ["Estrutura", "Autoridade", "Estabilidade"],
    upright: "Liderança, disciplina, ordem e proteção.",
    reversed: "Rigidez, controle excessivo, abuso de poder.",
    description:
      "O Imperador estabelece estrutura e fronteiras. Representa a figura paterna, a razão e a construção de bases sólidas.",
  },
  {
    slug: "o-hierofante",
    number: "V",
    name: "O Hierofante",
    type: "maior",
    keywords: ["Tradição", "Ensino", "Fé"],
    upright: "Sabedoria espiritual, instituições, valores compartilhados.",
    reversed: "Dogmatismo, rebeldia, quebra de convenções.",
    description:
      "O Hierofante é o mestre das tradições e o elo entre o sagrado e o cotidiano. Convida ao aprendizado dentro de estruturas estabelecidas.",
  },
  {
    slug: "os-enamorados",
    number: "VI",
    name: "Os Enamorados",
    type: "maior",
    keywords: ["União", "Escolha", "Harmonia"],
    upright: "Amor, parcerias, decisões alinhadas com os valores.",
    reversed: "Desequilíbrio, escolhas difíceis, desalinhamento.",
    description:
      "Os Enamorados falam de uniões e das escolhas que definem o caminho. Representam o encontro de opostos e a busca por harmonia.",
  },
  {
    slug: "o-carro",
    number: "VII",
    name: "O Carro",
    type: "maior",
    keywords: ["Vitória", "Vontade", "Direção"],
    upright: "Determinação, controle, avanço e conquista.",
    reversed: "Falta de rumo, agressividade, perda de controle.",
    description:
      "O Carro simboliza o triunfo conquistado pela vontade. Ensina a conduzir forças opostas na mesma direção rumo ao objetivo.",
  },
  {
    slug: "a-forca",
    number: "VIII",
    name: "A Força",
    type: "maior",
    keywords: ["Coragem", "Domínio", "Paciência"],
    upright: "Força interior, compaixão, controle suave dos instintos.",
    reversed: "Insegurança, impulsividade, dúvida sobre si.",
    description:
      "A Força revela o poder da gentileza sobre a brutalidade. É a coragem que doma os instintos com paciência e amor.",
  },
  {
    slug: "o-eremita",
    number: "IX",
    name: "O Eremita",
    type: "maior",
    keywords: ["Introspecção", "Busca", "Orientação"],
    upright: "Reflexão, sabedoria, busca por respostas internas.",
    reversed: "Isolamento, solidão excessiva, recusa em ouvir.",
    description:
      "O Eremita ilumina o caminho com sua lanterna interior. Representa o recolhimento necessário para encontrar a própria verdade.",
  },
  {
    slug: "a-roda-da-fortuna",
    number: "X",
    name: "A Roda da Fortuna",
    type: "maior",
    keywords: ["Ciclos", "Destino", "Mudança"],
    upright: "Sorte, viradas, ciclos naturais da vida.",
    reversed: "Resistência à mudança, má fase, falta de controle.",
    description:
      "A Roda da Fortuna gira constantemente, lembrando que tudo muda. Ensina a fluir com os ciclos e a aceitar o movimento do destino.",
  },
  {
    slug: "a-justica",
    number: "XI",
    name: "A Justiça",
    type: "maior",
    keywords: ["Equilíbrio", "Verdade", "Causa e efeito"],
    upright: "Honestidade, responsabilidade, decisões justas.",
    reversed: "Injustiça, desonestidade, fuga das consequências.",
    description:
      "A Justiça pesa as ações com imparcialidade. Representa a lei do karma e a importância da verdade e do equilíbrio.",
  },
  {
    slug: "o-enforcado",
    number: "XII",
    name: "O Enforcado",
    type: "maior",
    keywords: ["Pausa", "Rendição", "Nova perspectiva"],
    upright: "Entrega, sacrifício consciente, mudança de visão.",
    reversed: "Estagnação, resistência, sacrifícios em vão.",
    description:
      "O Enforcado vê o mundo de cabeça para baixo. Ensina que a rendição e a pausa podem revelar novas perspectivas.",
  },
  {
    slug: "a-morte",
    number: "XIII",
    name: "A Morte",
    type: "maior",
    keywords: ["Transformação", "Fim", "Renascimento"],
    upright: "Encerramento de ciclos, transformação profunda, recomeço.",
    reversed: "Resistência ao fim, medo de mudar, apego.",
    description:
      "A Morte raramente é literal: ela anuncia transformação. Representa o fim de um ciclo para que algo novo possa nascer.",
  },
  {
    slug: "a-temperanca",
    number: "XIV",
    name: "A Temperança",
    type: "maior",
    keywords: ["Equilíbrio", "Moderação", "Cura"],
    upright: "Harmonia, paciência, síntese e moderação.",
    reversed: "Excessos, desequilíbrio, impaciência.",
    description:
      "A Temperança mistura opostos com paciência alquímica. Ensina a arte do equilíbrio e da moderação para alcançar a cura.",
  },
  {
    slug: "o-diabo",
    number: "XV",
    name: "O Diabo",
    type: "maior",
    keywords: ["Apego", "Tentação", "Sombra"],
    upright: "Vícios, materialismo, prisões autoimpostas.",
    reversed: "Libertação, consciência, quebra de correntes.",
    description:
      "O Diabo revela as correntes que nós mesmos criamos. Convida a olhar para a sombra, os apegos e os desejos que aprisionam.",
  },
  {
    slug: "a-torre",
    number: "XVI",
    name: "A Torre",
    type: "maior",
    keywords: ["Ruptura", "Revelação", "Caos"],
    upright: "Mudança súbita, colapso de estruturas falsas, despertar.",
    reversed: "Medo da mudança, desastre evitado, resistência.",
    description:
      "A Torre desmorona o que foi construído em bases falsas. Embora abrupta, sua queda abre espaço para uma verdade mais sólida.",
  },
  {
    slug: "a-estrela",
    number: "XVII",
    name: "A Estrela",
    type: "maior",
    keywords: ["Esperança", "Inspiração", "Serenidade"],
    upright: "Fé renovada, cura, otimismo e propósito.",
    reversed: "Desânimo, falta de fé, desconexão.",
    description:
      "A Estrela brilha após a tempestade, trazendo esperança e inspiração. Representa a renovação da fé e a calma após o caos.",
  },
  {
    slug: "a-lua",
    number: "XVIII",
    name: "A Lua",
    type: "maior",
    keywords: ["Ilusão", "Intuição", "Inconsciente"],
    upright: "Sonhos, medos ocultos, intuição e mistério.",
    reversed: "Clareza, superação de medos, verdade revelada.",
    description:
      "A Lua ilumina o reino do inconsciente, das ilusões e dos sonhos. Convida a confiar na intuição em meio à incerteza.",
  },
  {
    slug: "o-sol",
    number: "XIX",
    name: "O Sol",
    type: "maior",
    keywords: ["Alegria", "Sucesso", "Vitalidade"],
    upright: "Felicidade, clareza, êxito e energia positiva.",
    reversed: "Otimismo turvo, atrasos, brilho temporário ofuscado.",
    description:
      "O Sol irradia alegria, sucesso e vitalidade. É a carta da clareza, da verdade e da celebração da vida.",
  },
  {
    slug: "o-julgamento",
    number: "XX",
    name: "O Julgamento",
    type: "maior",
    keywords: ["Despertar", "Renovação", "Chamado"],
    upright: "Renascimento, avaliação, chamado para um propósito maior.",
    reversed: "Autocrítica severa, dúvida, recusa ao chamado.",
    description:
      "O Julgamento anuncia um despertar e um chamado para algo maior. Representa o momento de avaliar o passado e renascer.",
  },
  {
    slug: "o-mundo",
    number: "XXI",
    name: "O Mundo",
    type: "maior",
    keywords: ["Realização", "Completude", "Integração"],
    upright: "Conclusão, conquista, plenitude e celebração.",
    reversed: "Ciclos inacabados, falta de fechamento, atrasos.",
    description:
      "O Mundo encerra a jornada do Louco com a sensação de completude. Representa a realização plena e a integração de todas as lições.",
  },
]

const suitRanks: { number: string; name: string }[] = [
  { number: "Ás", name: "Ás" },
  { number: "2", name: "Dois" },
  { number: "3", name: "Três" },
  { number: "4", name: "Quatro" },
  { number: "5", name: "Cinco" },
  { number: "6", name: "Seis" },
  { number: "7", name: "Sete" },
  { number: "8", name: "Oito" },
  { number: "9", name: "Nove" },
  { number: "10", name: "Dez" },
  { number: "Pajem", name: "Pajem" },
  { number: "Cavaleiro", name: "Cavaleiro" },
  { number: "Rainha", name: "Rainha" },
  { number: "Rei", name: "Rei" },
]

const minorMeanings: Record<MinorSuit, { upright: string[]; reversed: string[]; desc: string[]; kw: string[][] }> = {
  paus: {
    kw: [
      ["Inspiração", "Potencial", "Início"],
      ["Planejamento", "Decisão", "Futuro"],
      ["Expansão", "Visão", "Progresso"],
      ["Celebração", "Lar", "Estabilidade"],
      ["Conflito", "Competição", "Tensão"],
      ["Vitória", "Reconhecimento", "Confiança"],
      ["Defesa", "Coragem", "Persistência"],
      ["Rapidez", "Movimento", "Notícias"],
      ["Resiliência", "Cautela", "Limite"],
      ["Sobrecarga", "Responsabilidade", "Esforço"],
      ["Exploração", "Entusiasmo", "Descoberta"],
      ["Ousadia", "Impulso", "Aventura"],
      ["Carisma", "Determinação", "Liderança"],
      ["Visão", "Liderança", "Empreendimento"],
    ],
    upright: [
      "Faísca de inspiração, novo projeto criativo e potencial em ação.",
      "Planejamento do futuro, decisões e o primeiro passo de uma jornada.",
      "Expansão, visão de longo prazo e progresso em andamento.",
      "Celebração, harmonia no lar e marcos felizes.",
      "Conflitos saudáveis, competição e energia dispersa.",
      "Vitória pública, reconhecimento e autoconfiança.",
      "Defender a própria posição com coragem e persistência.",
      "Movimento rápido, notícias e progresso acelerado.",
      "Resiliência diante do cansaço, cautela e defesa.",
      "Carregar peso em excesso, responsabilidades acumuladas.",
      "Entusiasmo de explorar, descobertas e curiosidade.",
      "Ação impulsiva, aventura e energia em movimento.",
      "Carisma, paixão e determinação para liderar.",
      "Liderança visionária, empreendedorismo e domínio criativo.",
    ],
    reversed: [
      "Atrasos criativos, falta de direção e ideias paradas.",
      "Medo do desconhecido, falta de planejamento.",
      "Atrasos, obstáculos e planos frustrados.",
      "Instabilidade no lar, transições difíceis.",
      "Evitar conflitos, tensão reprimida.",
      "Falta de reconhecimento, insegurança.",
      "Sentir-se sobrecarregado, ceder à pressão.",
      "Pressa excessiva, comunicação atrapalhada.",
      "Teimosia, esgotamento, defensividade.",
      "Delegar tarefas, aliviar fardos.",
      "Inquietação, falta de foco, adiar planos.",
      "Imprudência, atrasos e frustração.",
      "Ciúmes, impulsividade, energia mal direcionada.",
      "Autoritarismo, decisões precipitadas.",
    ],
    desc: [
      "O Ás de Paus traz a centelha inicial da inspiração e do desejo de criar.",
      "O Dois de Paus fala de planejamento e da escolha de um caminho a seguir.",
      "O Três de Paus indica expansão e a recompensa de olhar adiante.",
      "O Quatro de Paus celebra estabilidade, festas e harmonia.",
      "O Cinco de Paus mostra competição e desafios que estimulam o crescimento.",
      "O Seis de Paus anuncia vitória, reconhecimento e confiança renovada.",
      "O Sete de Paus pede que se defenda aquilo que se conquistou.",
      "O Oito de Paus traz velocidade, notícias e eventos em rápido movimento.",
      "O Nove de Paus mostra resiliência mesmo diante do cansaço.",
      "O Dez de Paus revela o peso das responsabilidades assumidas.",
      "O Pajem de Paus é o mensageiro entusiasmado de novas ideias.",
      "O Cavaleiro de Paus avança com ousadia, paixão e impulso.",
      "A Rainha de Paus irradia carisma, calor e determinação.",
      "O Rei de Paus lidera com visão, coragem e empreendedorismo.",
    ],
  },
  copas: {
    kw: [
      ["Amor", "Novos sentimentos", "Intuição"],
      ["Parceria", "Atração", "União"],
      ["Amizade", "Celebração", "Comunidade"],
      ["Apatia", "Contemplação", "Tédio"],
      ["Perda", "Luto", "Decepção"],
      ["Nostalgia", "Memórias", "Inocência"],
      ["Ilusão", "Escolhas", "Fantasia"],
      ["Abandono", "Busca", "Mudança"],
      ["Satisfação", "Desejos", "Gratidão"],
      ["Harmonia", "Família", "Plenitude"],
      ["Sensibilidade", "Criatividade", "Mensagem"],
      ["Romance", "Charme", "Idealismo"],
      ["Compaixão", "Acolhimento", "Intuição"],
      ["Equilíbrio emocional", "Generosidade", "Calma"],
    ],
    upright: [
      "Transbordar de emoções, amor novo e abertura espiritual.",
      "Conexão mútua, parcerias e atração profunda.",
      "Amizade, comemoração e apoio da comunidade.",
      "Apatia, contemplação e oportunidades não percebidas.",
      "Luto, decepção e foco na perda.",
      "Nostalgia, lembranças felizes e reencontros.",
      "Muitas opções, ilusões e sonhos a serem filtrados.",
      "Deixar para trás o que não satisfaz em busca de algo maior.",
      "Contentamento emocional, desejos realizados e gratidão.",
      "Plenitude familiar, harmonia e felicidade duradoura.",
      "Sensibilidade, criatividade e mensagens emocionais.",
      "Romance, charme e propostas vindas do coração.",
      "Compaixão, acolhimento e profunda intuição.",
      "Maturidade emocional, generosidade e serenidade.",
    ],
    reversed: [
      "Emoções reprimidas, vazio interior, amor bloqueado.",
      "Desequilíbrio na relação, rupturas e tensões.",
      "Conflitos sociais, isolamento, desentendimentos.",
      "Despertar, aceitar oportunidades, sair do tédio.",
      "Aceitação, perdão e seguir em frente.",
      "Preso ao passado, idealizar o que foi.",
      "Clareza nas escolhas, dissipar ilusões.",
      "Medo de mudar, voltar ao conhecido.",
      "Insatisfação apesar das conquistas.",
      "Desarmonia familiar, valores em conflito.",
      "Insegurança emocional, criatividade bloqueada.",
      "Promessas vazias, instabilidade emocional.",
      "Dependência emocional, carência.",
      "Frieza emocional, repressão de sentimentos.",
    ],
    desc: [
      "O Ás de Copas anuncia um novo fluxo de amor e emoção.",
      "O Dois de Copas celebra a união e a conexão entre duas pessoas.",
      "O Três de Copas reúne amigos em celebração e apoio mútuo.",
      "O Quatro de Copas mostra apatia e oportunidades ignoradas.",
      "O Cinco de Copas trata do luto e do foco naquilo que se perdeu.",
      "O Seis de Copas evoca nostalgia, memórias e inocência.",
      "O Sete de Copas apresenta múltiplas opções e ilusões.",
      "O Oito de Copas fala de abandonar o que já não basta.",
      "O Nove de Copas é a carta dos desejos realizados.",
      "O Dez de Copas representa plenitude emocional e familiar.",
      "O Pajem de Copas traz mensagens sensíveis e criativas.",
      "O Cavaleiro de Copas avança guiado pelo romance e ideal.",
      "A Rainha de Copas acolhe com compaixão e intuição.",
      "O Rei de Copas equilibra emoção e razão com serenidade.",
    ],
  },
  espadas: {
    kw: [
      ["Clareza", "Verdade", "Ruptura mental"],
      ["Indecisão", "Impasse", "Trégua"],
      ["Mágoa", "Dor", "Tristeza"],
      ["Descanso", "Recuperação", "Pausa"],
      ["Conflito", "Derrota", "Tensão"],
      ["Transição", "Passagem", "Alívio"],
      ["Estratégia", "Cautela", "Engano"],
      ["Limitação", "Prisão mental", "Medo"],
      ["Ansiedade", "Pesadelos", "Preocupação"],
      ["Fim doloroso", "Crise", "Rendição"],
      ["Curiosidade", "Vigilância", "Verdade"],
      ["Ação rápida", "Lógica", "Determinação"],
      ["Imparcialidade", "Clareza", "Independência"],
      ["Autoridade intelectual", "Verdade", "Disciplina"],
    ],
    upright: [
      "Avanço mental, verdade nítida e novas ideias rompendo barreiras.",
      "Decisão difícil, impasse e equilíbrio precário.",
      "Mágoa, dor emocional e revelações dolorosas.",
      "Descanso necessário, recuperação e contemplação.",
      "Conflito, derrota e vitórias vazias.",
      "Transição rumo a águas mais calmas.",
      "Estratégia, cautela e jogos mentais.",
      "Sensação de limitação e prisões da própria mente.",
      "Ansiedade, preocupação e pensamentos noturnos.",
      "Fim doloroso, fundo do poço e rendição.",
      "Curiosidade mental, vigilância e busca pela verdade.",
      "Pensamento veloz, lógica afiada e ação decidida.",
      "Imparcialidade, clareza e independência intelectual.",
      "Autoridade da razão, verdade e disciplina mental.",
    ],
    reversed: [
      "Confusão mental, ideias bloqueadas, falta de clareza.",
      "Decisão tomada, sair do impasse.",
      "Cura da mágoa, perdão e recuperação.",
      "Retomar a ação, esgotamento, inquietude.",
      "Reconciliação, fim do conflito.",
      "Resistência à mudança, bagagem emocional.",
      "Confissão, mudança de estratégia.",
      "Libertação mental, superação do medo.",
      "Alívio da ansiedade, enfrentar os medos.",
      "Recuperação, evitar o pior, renascer.",
      "Fofoca, dispersão, falta de foco.",
      "Impulsividade, pressa e agressividade.",
      "Frieza, julgamento severo, isolamento.",
      "Tirania, manipulação, racionalidade excessiva.",
    ],
    desc: [
      "O Ás de Espadas corta as ilusões com clareza e verdade.",
      "O Dois de Espadas mostra um impasse que exige decisão.",
      "O Três de Espadas representa a dor de uma mágoa profunda.",
      "O Quatro de Espadas convida ao descanso e à recuperação.",
      "O Cinco de Espadas trata de conflitos e vitórias vazias.",
      "O Seis de Espadas leva de águas turbulentas a outras mais calmas.",
      "O Sete de Espadas alerta para estratégia, astúcia e engano.",
      "O Oito de Espadas revela prisões criadas pela própria mente.",
      "O Nove de Espadas expressa ansiedade e noites de preocupação.",
      "O Dez de Espadas marca o fim doloroso e o fundo do poço.",
      "O Pajem de Espadas é curioso, vigilante e sedento por verdade.",
      "O Cavaleiro de Espadas avança veloz, guiado pela lógica.",
      "A Rainha de Espadas julga com clareza e imparcialidade.",
      "O Rei de Espadas governa pela razão, verdade e disciplina.",
    ],
  },
  ouros: {
    kw: [
      ["Oportunidade", "Prosperidade", "Início material"],
      ["Equilíbrio", "Adaptação", "Malabarismo"],
      ["Colaboração", "Maestria", "Trabalho em equipe"],
      ["Segurança", "Posse", "Controle"],
      ["Dificuldade", "Perda", "Insegurança"],
      ["Generosidade", "Troca", "Caridade"],
      ["Avaliação", "Paciência", "Investimento"],
      ["Dedicação", "Aprimoramento", "Habilidade"],
      ["Independência", "Conforto", "Autossuficiência"],
      ["Riqueza", "Legado", "Estabilidade"],
      ["Estudo", "Planejamento", "Manifestação"],
      ["Diligência", "Rotina", "Confiabilidade"],
      ["Prosperidade", "Praticidade", "Nutrição"],
      ["Abundância", "Sucesso", "Segurança"],
    ],
    upright: [
      "Nova oportunidade material, prosperidade e prosperar.",
      "Equilíbrio entre prioridades e adaptação às mudanças.",
      "Trabalho em equipe, maestria e colaboração.",
      "Segurança material, controle e apego ao que se tem.",
      "Dificuldades financeiras, perda e insegurança.",
      "Generosidade, troca justa e caridade.",
      "Avaliar progresso, paciência e investimentos.",
      "Dedicação ao ofício e aprimoramento de habilidades.",
      "Independência, conforto e autossuficiência.",
      "Riqueza duradoura, legado e estabilidade familiar.",
      "Estudo, planejamento e manifestar metas.",
      "Trabalho diligente, rotina e confiabilidade.",
      "Prosperidade prática e cuidado nutridor.",
      "Abundância, sucesso material e segurança plena.",
    ],
    reversed: [
      "Oportunidade perdida, planos materiais frustrados.",
      "Desorganização financeira, sobrecarga.",
      "Falta de trabalho em equipe, qualidade comprometida.",
      "Apego excessivo, ganância, insegurança.",
      "Recuperação financeira, fim das dificuldades.",
      "Dívidas, generosidade com segundas intenções.",
      "Impaciência, investimentos mal feitos.",
      "Perfeccionismo, esforço sem propósito.",
      "Dependência material, excessos.",
      "Instabilidade financeira, conflitos por herança.",
      "Falta de foco nos estudos, planos no papel.",
      "Tédio, estagnação, falta de progresso.",
      "Insegurança material, descuido com o próprio bem-estar.",
      "Insegurança financeira, controle excessivo.",
    ],
    desc: [
      "O Ás de Ouros semeia uma nova oportunidade de prosperidade.",
      "O Dois de Ouros equilibra prioridades em constante movimento.",
      "O Três de Ouros valoriza colaboração e maestria no trabalho.",
      "O Quatro de Ouros mostra o apego à segurança e à posse.",
      "O Cinco de Ouros trata da dificuldade material e do desamparo.",
      "O Seis de Ouros celebra generosidade e trocas justas.",
      "O Sete de Ouros convida à paciência e à avaliação dos frutos.",
      "O Oito de Ouros é a carta da dedicação e do aprimoramento.",
      "O Nove de Ouros desfruta de conforto e autossuficiência.",
      "O Dez de Ouros representa riqueza, legado e estabilidade.",
      "O Pajem de Ouros estuda e planeja a manifestação de metas.",
      "O Cavaleiro de Ouros trabalha com diligência e constância.",
      "A Rainha de Ouros nutre com praticidade e prosperidade.",
      "O Rei de Ouros colhe abundância, sucesso e segurança.",
    ],
  },
}

function buildMinorArcana(): TarotCard[] {
  const cards: TarotCard[] = []
  ;(Object.keys(suitInfo) as MinorSuit[]).forEach((suit) => {
    const meanings = minorMeanings[suit]
    suitRanks.forEach((rank, i) => {
      cards.push({
        slug: `${rank.number.toLowerCase()}-de-${suit}`,
        number: rank.number,
        name: `${rank.name} de ${suitInfo[suit].name}`,
        type: "menor",
        suit,
        keywords: meanings.kw[i],
        upright: meanings.upright[i],
        reversed: meanings.reversed[i],
        description: meanings.desc[i],
      })
    })
  })
  return cards
}

export const minorArcana: TarotCard[] = buildMinorArcana()

export const allCards: TarotCard[] = [...majorArcana, ...minorArcana]

export function getCardBySlug(slug: string): TarotCard | undefined {
  return allCards.find((c) => c.slug === slug)
}
